openapi: 3.1.0
info:
  version: 1.0.0
  title: Node.js Contacts API
  description: API documentation for Contacts management app with Auth
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-production-6f89.up.railway.app/
paths:
  /auth/register:
    $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    $ref: ../swagger/paths/auth/logout.yaml
  /auth/current:
    $ref: ../swagger/paths/auth/current.yaml
  /auth/send-reset-email:
    $ref: ../swagger/paths/auth/send-reset-email.yaml
  /auth/reset-pwd:
    $ref: ../swagger/paths/auth/reset-pwd.yaml
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{contactId}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{contactId}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{contactId}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
